### ISSUE TITLE
Setting "class" for SVG doesn't work

### ISSUE THREAD

**Issue by tailhook** [joelrich/citojs#16]
It seems that `className` doesn't work for SVG elements (at least in chrome 40). The `classList` works. And `setAttribute("class", ...)` works too. Ironically when I comment out `className` hack, it works in chrome:
```
                    //if (attrName === 'class') {
                    //    domElement.className = attrValue;
                    //} else {
                        updateAttribute(domElement, attrName, attrValue);
                    //}
```
I'm not sure how well this will work in other browsers.

**Comment by Auxolust** [comment]
Svgs classes do not work like normal html elements, To modify classes on svgs, you have to modify the class attribute via setAttribute rather than manipulating the standard class properties

**Comment by tailhook** [comment]
Okay, @Auxolust confirms that it's standard behavior (not chrome bug). What's solution in cito.js? Should it hardcode for svg? Or maybe always use `setAttribute`? (which seems to work for html classes too, not sure how fast though)

**Comment by Auxolust** [comment]
@tailhook  See http://jsperf.com/style-vs-classname/4 . I think @joelrich  would prefer to optimize for speed using a hardcode, so the solution should simply be 

````js
if (attrName === 'class' && tag !='svg') 
{
    domElement.className = attrValue;
  } 
else
 {
    updateAttribute(domElement, attrName, attrValue);
}
```

but ultimately it depends how @joelrich wants to hand it

**Comment by tailhook** [comment]
@Auxolust, well, it's not just "svg" tag, but all the tags inside. So it's unclear how to check for that (probably check dom element's namespace?)

Also interesting enough, if I read from ".className" but write using "setAttribute" in that test, it's faster than writing to ".className", at least in my chrome 41.

**Comment by Auxolust** [comment]
@tailhook  Aye, wasn't even considering svg subelements, in which case you are right , the element namespace should help deduce when to use set attribute.

**Comment by joelrich** [comment]
You would probably hate me if you knew why I used className there. Feel free to make a few more guesses :-)

**Comment by jails** [comment]
IE < 8 compatibility ? Otherwise `setAttribute` would just work fine for all others.

**Comment by joelrich** [comment]
Yep, there was in IE issue...
