### ISSUE TITLE
Maximum call stack size exceeded or what I'm doing wrong?

### ISSUE THREAD

**Issue by vird** [joelrich/citojs#19]
This code causes Maximum call stack size exceeded

    window.test = function() {
      window.binding = ['lvl3'];
      window.tree = {
        tag: 'div',
        children: [
          'lvl1', {
            tag: 'div',
            children: [
              'lvl2', {
                tag: 'div',
                children: binding
              }
            ]
          }
        ]
      };
      window.node = cito.vdom.append(document.body, tree);
      window.binding[0] = "replaced";
      return cito.vdom.updateChildren(node, tree); //here is exception
    };

    at createNode (http://localhost:1337/3rdparty/cito.js:265:21)
    at createAllChildren (http://localhost:1337/3rdparty/cito.js:796:17)

**Comment by vird** [comment]
even this https://gist.github.com/vird/dec1e747b92886eb357f didn't help.
cito doesn't create .dom property in binding variable for some reason

**Comment by joelrich** [comment]
You cannot reuse a virtual dom tree, but the following should work fine:
```javascript
var binding = ['lvl3'];

function tree() {
    return {
        tag: 'div',
        children: [
            'lvl1',
            {
                tag: 'div',
                children: [
                    'lvl2', {
                        tag: 'div',
                        children: binding
                    }
                ]
            }
        ]
    };
}

var node = cito.vdom.append(document.body, tree);
binding[0] = "replaced";
cito.vdom.updateChildren(node, tree);
```
