### ISSUE TITLE
Is citojs ready for production?

### ISSUE THREAD

**Issue by timuric** [joelrich/citojs#2]
I am looking at virtual-dom implementations for my next mobile web app project. Looks like Citojs is fastest kid around http://vdom-benchmark.github.io/vdom-benchmark/ 
Would be wise to use Citojs in production already? And do you think it would be suitable for mobile (cordova based) apps? Thank you in advance.

**Comment by joelrich** [comment]
Thanks for your interest. I would not recommend to use cito.js in production at the moment. I am less concerned about problems in production than braking API changes in the near future. This is still a research project and I am reconsidering several design decisions at the moment (which is taking some time).

**Comment by joelrich** [comment]
Once I have decided how to continue with cito.js, I will let you know. I expect this to be in about two weeks.

**Comment by gaydenko** [comment]
@joelrich , have you now at least a small hint with regard to that degree the API can be changed? :) Especially I'm interested in hyperscripting (which at cito.js case takes just a form of JS objects), as far as it will demand the main rewriting at case of significant change.

**Comment by llambda** [comment]
Currently mithril user here...exciting project.....I like your approach @joelrich :+1:

**Comment by joelrich** [comment]
@gaydenko sure, I have just explained my ideas here: https://github.com/joelrich/citojs/issues/18

**Comment by gaydenko** [comment]
> I have just explained my ideas here: #18 (comment)

@joelrich , thanks for the clarification. Sorry, I was forced to make decision earlier and have switched to (and am working with) [Trackira](https://github.com/trackira/trackira) (it's also very fast already).
