### ISSUE TITLE
Error occurred while removing Node.

### ISSUE THREAD

**Issue by RubaXa** [joelrich/citojs#20]
Error: `Uncaught TypeError: Cannot read property 'removeChild' of null`

---

Examples:
 - does not work: http://jsbin.com/yuzisab/edit?js,output
 - working: http://jsbin.com/kahufi/edit?js,output

**Comment by RubaXa** [comment]
@joelrich How dangerous can be this "hack"?

```js
// Before call `cito.vdom.remove` update `children`, and `dom`
old.dom = null;
old.children = old.children.filter(function (node) {
  if (node.dom && node.dom.parentNode) {
    old.dom = old.dom || node.dom;
    return true;
  }
});
old.domLength = old.children.length;

cito.vdom.remove(old);
```

**Comment by joelrich** [comment]
@RubaXa have you already found out when exactly this problem happens? A smaller example to reproduce it would be very helpful. I will then try to fix it on Wednesday.

**Comment by RubaXa** [comment]
@joelrich All the matter in `vnode.dom`, when using `fragment`:
http://jsbin.com/peqexu/edit?js,console,output

```js
var vdom = cito.vdom.append(box, {
  tag: 'div',
  children: [
    {
      children: [
        {tag: 'div', children: 'foo'}
      ]
    }
  ]
});

cito.vdom.update(vdom, {
  tag: 'div',
  children: [
    {
      children: [
        {
          children: [
            {tag: 'div', children: 'bar'}
          ]
        },
        {tag: 'div', children: 'foo'}
      ]
    }
  ]
});

// Remove 'bar'
cito.vdom.remove(vdom.children[0].children[0]);

// Remove 'foo'  <--  ERROR
cito.vdom.remove(vdom.children[0]);

```

**Comment by RubaXa** [comment]
```
<div>
  + #fragment
  |--+ #fragment         // remove (2)
  |  |-- <div>bar</div>  // remove (1)
  |-- <div>foo</div>
</div>
```

**Comment by joelrich** [comment]
@RubaXa Ah, now I understand. I have never intended cito.vdom.remove to remove specific subtrees. Instead, it is just meant to remove a whole rendered virtual dom tree (and clean up everything). Wouldn't it be possible to re-render the whole tree but this time without the part which should be removed? Ideally, virtual dom should only be used declaratively. Otherwise, you could also just use an imperative library. Does that make sense?

**Comment by RubaXa** [comment]
I want to add css-animation when adding and removing a fragment if you know how to do it in another way, it would be curious to see it.

For now, I left the "hack" described above: https://github.com/joelrich/citojs/issues/20#issuecomment-143706661

**Comment by joelrich** [comment]
At the moment, you would have to handle this by yourself with different states. Example:

```javascript
function div(state) {
	return state.removed ? [] : [{tag: 'div', class: 'my-div' + (state.removing ? ' is-removing' : '')}];
}
```
I know, this is far from ideal. In the future, this will be doable with lifecycle events.
