### ISSUE TITLE
Is it possible to use citojs with other doms?

### ISSUE THREAD

**Issue by user471** [joelrich/citojs#22]
For example, libraries like pixi.js, three.js, nativescript have their own dom.
Or is it only support html?

**Comment by joelrich** [comment]
I am not sure if I understand your question. Can you give me an example?

**Comment by user471** [comment]
For example, instead of calling ```document.createElement(tagName)``` directly, it could use some abstract layer. 
```
DomManipulator = {
     createElement = ....
     ...
}
```
So, there could be different implementations

HtmlDomApi = {
     createElement = document.createElement
     ...
}

PixiDomApi = {
    createElement = Pixi.createElement
    ....
}
etc
```
So, it would work with any doms and not just html.

**Comment by joelrich** [comment]
This is not possible at the moment. In theory it would be possible to introduce an abstraction layer with which you can support arbitrary targets (like canvas, native...), but at the moment I don't have time for such a change.
