### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by sprat** [joelrich/citojs#24]
I've seen some discussions about the future of citojs, a big refactoring in progress, stopped due to lack of time to devote on the project. I really like the API as it is now, so and I would like to use it in my library/application (or at least try it).

However, I can't really because:
- the project is not available in NPM
- there's no UMD/AMD/CJS wrapper around the dist code
- there's no index file so that it can be used with browserify for example
- there's no version officially released?

Could you please consider packaging a version of the current API?

**Comment by barneycarroll** [comment]
In the works :)

**Comment by sprat** [comment]
Nice, thank you! I can't wait to see that done ;)

**Comment by trueadm** [comment]
@barneycarroll are you now maintaining Cito too?

**Comment by barneycarroll** [comment]
@trueadm hiya, yeah was chatting to Joel and he doesn't have any time for this ATM, but I'd quite like to get it to v1 as implied by the README & open issues. I'm interested by the level of control it sits in the fragment identification, diffing and patching processes, which IMO makes it interesting to maintain in parallel to other focused vDOM optimisation paths.

**Comment by sprat** [comment]
Speaking of v1, I think #8 should be addressed too. So here, it would be a v < 1.

**Comment by barneycarroll** [comment]
Yeah, #8 is a priority. But it's a new feature request - not expected functionality according to the documentation.  Suggest we conceive of v1 as a feature-complete implementation according to the current README. Separate properties and attribute maps is currently scheduled for 1.1, highest priority post 1.0.

**Comment by sprat** [comment]
Ok, no problem!

**Comment by trueadm** [comment]
@barneycarroll great to hear that Cito is getting some TLC. Many of the core ideas and structures from Cito 0.2 were the basis for the Inferno 0.4 re-write. Please also add to the roadmap breaking Cito down and moving to ES6 so others can tree-shake Cito with tools like `rollup`. That'd be awesome.

**Comment by sprat** [comment]
Any progress on this subject? Need some help?

**Comment by barneycarroll** [comment]
@sprat no progress this end — day job is throwing everything it's got at me & both my laptops have died. PRs welcome!

**Comment by sprat** [comment]
Here's my pull request. Hope it's ok to merge.
