### ISSUE TITLE
events - focus lost

### ISSUE THREAD

**Issue by marcorra** [joelrich/citojs#7]
Hi, @joelrich  Just try this code, and you should get the point.

```javascript

var items = [
    {id: 1, name: "a"},
    {id: 2, name: "b"},
    {id: 3, name: "c"}
]
function reverse() {
    items.reverse()
    cito.vdom.update(rootNode, root)
}

function root() {
    return {tag: "div", children: items.map(function(item) {
        return {
            tag: "input",
            attrs: {
                key: item.id,
                value: item.name
            }
        }
    })}
}

var rootNode = cito.vdom.append(document.body, root);

setInterval(reverse, 2000)

//click on first input
//expected: focus should jump to third input after 2 seconds, then back to first input after 2 seconds, etc
//actual: focus is lost
```

**Comment by joelrich** [comment]
I will implement a fix with document.activeElement to keep the focus.
Please note that you have to use the key property directly in the node object, for example
```{tag: 'input', key: item.id, attrs: {value: item.name}}```

**Comment by marcorra** [comment]
@joelrich I experimented to figure out where to put the key to get things work. Therefor not correct.

For document.activeElement just be aware that there are issues with IE browsers ( 8 - 10 ), and also with iFrames. So you would need a workaround here.

I suggest you should check you gmail innbox.
